### ISSUE TITLE
А мож переехать с Github Pages на Surge?

### ISSUE THREAD

**Issue by emoticon** [pekach/pekach#4]
Просто там роутинг будет 100% правильно работать, то есть, если назвать индекс 200.html, то оно будет перенаправлять все запросы на этот файл.
Я именно про [это](https://surge.sh/), если что.

**Comment by JAremko** [comment]
https://help.github.com/articles/redirects-on-github-pages/ :pled:

**Comment by JAremko** [comment]
Так блэд. Кто хочет дешевой популярности? Нужно конфиг для этого плагина генерить из ангуляр роутеров.

**Comment by emoticon** [comment]
@JAremko вам CLI надо?

**Comment by JAremko** [comment]
@emoticon  нам надо код :grumpy:

**Comment by JAremko** [comment]
хотя мож проще сделать свою 404  https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by JAremko** [comment]
Идиально было бы генерить статические страницы в нашом CI деплой скрипте через чето в духе https://universal.angular.io/quickstart/ но @ichursin  говорит что это слишком много кода.

**Comment by emoticon** [comment]
@JAremko будет же 404 респонс код

**Comment by JAremko** [comment]
@emoticon  Мож можно редирект настроить всетаки как-то с 404 на главную или в нее впердолить `<meta http-equiv="refresh" ..>` но это все как-то неочень. Мы пока просто откатили на # роутер :pled:

**Comment by emoticon** [comment]
@JAremko я уже парсер роутов написал, пишу генератор конфига , кек

**Comment by JAremko** [comment]
@ichursin  вкинул еще вариант с готовой копипастой https://github.com/websemantics/gh-pages-spa/blob/master/ghspa.js

**Comment by emoticon** [comment]
@JAremko круто

**Comment by emoticon** [comment]
@JAremko на каком варианте остановимся?

**Comment by emoticon** [comment]
@JAremko меня смущает, что у вас не Jekyll

**Comment by JAremko** [comment]
Ты в дескорде есть :spk: ?  а то у нас там обсуждение активное

**Comment by emoticon** [comment]
@JAremko кнеш есть

**Comment by emoticon** [comment]
andrey#0534
